FROM alpine:3.18

WORKDIR /pb

COPY pocketbase.exe ./pocketbase

RUN apk add --no-cache libc6-compat \
    && chmod +x pocketbase

EXPOSE 8090

ENTRYPOINT ["./pocketbase", "serve", "--http", "0.0.0.0:8090"]
